use std::env;
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::net::SocketAddr;
use std::os::unix::fs::OpenOptionsExt;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;

use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use clap::Parser;
use rand::RngCore;
use serde::{Deserialize, Serialize};

use crate::{Error, Result};

const DEFAULT_DISCONNECT_GRACE_SECS: u64 = 30;
const DEFAULT_IDLE_TIMEOUT_SECS: u64 = 300;
const DEFAULT_SHUTDOWN_TIMEOUT_SECS: u64 = 5;
const DEFAULT_MAX_BACKUP_BYTES: u64 = 256 * 1024 * 1024;

#[derive(Debug, Parser)]
#[command(name = "openhouse-pi-runtime", version, about)]
pub struct Args {
    /// Loopback address used by the HTTP and WebSocket server.
    #[arg(long, env = "OPENHOUSE_PI_LISTEN", default_value = "127.0.0.1:8765")]
    pub listen: SocketAddr,

    /// `pi_agent_rust` executable (or an absolute path to it).
    #[arg(long, env = "OPENHOUSE_PI_BIN", default_value = "pi")]
    pub pi_bin: PathBuf,

    /// Root containing Pi JSONL conversation files.
    #[arg(long, env = "OPENHOUSE_PI_SESSIONS_DIR")]
    pub sessions_dir: Option<PathBuf>,

    /// Runtime state directory. It never stores provider credentials.
    #[arg(long, env = "OPENHOUSE_PI_STATE_DIR")]
    pub state_dir: Option<PathBuf>,

    /// Working directory inherited by Pi subprocesses.
    #[arg(long, env = "OPENHOUSE_PI_WORKING_DIR")]
    pub pi_working_dir: Option<PathBuf>,

    /// Pi extension entrypoint or manifest directory. May be repeated.
    #[arg(
        long = "extension",
        env = "OPENHOUSE_PI_EXTENSIONS",
        value_delimiter = ','
    )]
    pub extension_paths: Vec<PathBuf>,

    /// Bearer token. Prefer `OPENHOUSE_PI_TOKEN` or `--token-file` in production.
    #[arg(long, env = "OPENHOUSE_PI_TOKEN", hide = true)]
    pub token: Option<String>,

    /// File containing the bearer token. Created securely when absent.
    #[arg(long, env = "OPENHOUSE_PI_TOKEN_FILE")]
    pub token_file: Option<PathBuf>,

    /// Seconds a disconnected controller can reclaim its lease.
    #[arg(long, env = "OPENHOUSE_PI_DISCONNECT_GRACE_SECS")]
    pub disconnect_grace_secs: Option<u64>,

    /// Seconds an unattached, inactive Pi process may remain alive.
    #[arg(long, env = "OPENHOUSE_PI_IDLE_TIMEOUT_SECS")]
    pub idle_timeout_secs: Option<u64>,

    /// Graceful shutdown window before a Pi process is killed.
    #[arg(long, env = "OPENHOUSE_PI_SHUTDOWN_TIMEOUT_SECS")]
    pub shutdown_timeout_secs: Option<u64>,

    /// Maximum uncompressed bytes accepted or generated by backup operations.
    #[arg(long, env = "OPENHOUSE_PI_MAX_BACKUP_BYTES")]
    pub max_backup_bytes: Option<u64>,
}

#[derive(Clone)]
pub struct Config {
    pub listen: SocketAddr,
    pub pi_bin: PathBuf,
    pub sessions_dir: PathBuf,
    pub state_dir: PathBuf,
    pub pi_working_dir: PathBuf,
    pub extension_paths: Vec<PathBuf>,
    pub token: Arc<str>,
    pub token_file: PathBuf,
    pub settings: Arc<RuntimeSettings>,
}

impl std::fmt::Debug for Config {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("Config")
            .field("listen", &self.listen)
            .field("pi_bin", &self.pi_bin)
            .field("sessions_dir", &self.sessions_dir)
            .field("state_dir", &self.state_dir)
            .field("pi_working_dir", &self.pi_working_dir)
            .field("extension_paths", &self.extension_paths)
            .field("token", &"[REDACTED]")
            .field("token_file", &self.token_file)
            .field("settings", &self.settings.snapshot())
            .finish()
    }
}

#[derive(Debug)]
pub struct RuntimeSettings {
    disconnect_grace_secs: AtomicU64,
    idle_timeout_secs: AtomicU64,
    shutdown_timeout_secs: AtomicU64,
    max_backup_bytes: AtomicU64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SettingsSnapshot {
    pub disconnect_grace_seconds: u64,
    pub idle_timeout_seconds: u64,
    pub shutdown_timeout_seconds: u64,
    pub max_backup_bytes: u64,
}

#[derive(Debug, Default, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SettingsPatch {
    pub disconnect_grace_seconds: Option<u64>,
    pub idle_timeout_seconds: Option<u64>,
    pub shutdown_timeout_seconds: Option<u64>,
    pub max_backup_bytes: Option<u64>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PublicConfig {
    pub listen: String,
    pub pi_bin: String,
    pub sessions_dir: String,
    pub state_dir: String,
    pub pi_working_dir: String,
    pub extension_paths: Vec<String>,
    pub token_file: String,
    #[serde(flatten)]
    pub settings: SettingsSnapshot,
}

impl RuntimeSettings {
    fn new(snapshot: &SettingsSnapshot) -> Self {
        Self {
            disconnect_grace_secs: AtomicU64::new(snapshot.disconnect_grace_seconds),
            idle_timeout_secs: AtomicU64::new(snapshot.idle_timeout_seconds),
            shutdown_timeout_secs: AtomicU64::new(snapshot.shutdown_timeout_seconds),
            max_backup_bytes: AtomicU64::new(snapshot.max_backup_bytes),
        }
    }

    pub fn snapshot(&self) -> SettingsSnapshot {
        SettingsSnapshot {
            disconnect_grace_seconds: self.disconnect_grace_secs.load(Ordering::Relaxed),
            idle_timeout_seconds: self.idle_timeout_secs.load(Ordering::Relaxed),
            shutdown_timeout_seconds: self.shutdown_timeout_secs.load(Ordering::Relaxed),
            max_backup_bytes: self.max_backup_bytes.load(Ordering::Relaxed),
        }
    }

    pub fn disconnect_grace(&self) -> Duration {
        Duration::from_secs(self.disconnect_grace_secs.load(Ordering::Relaxed))
    }

    pub fn idle_timeout(&self) -> Duration {
        Duration::from_secs(self.idle_timeout_secs.load(Ordering::Relaxed))
    }

    pub fn shutdown_timeout(&self) -> Duration {
        Duration::from_secs(self.shutdown_timeout_secs.load(Ordering::Relaxed))
    }

    pub fn max_backup_bytes(&self) -> u64 {
        self.max_backup_bytes.load(Ordering::Relaxed)
    }

    pub fn apply(&self, patch: &SettingsPatch) -> Result<SettingsSnapshot> {
        let mut next = self.snapshot();
        if let Some(value) = patch.disconnect_grace_seconds {
            next.disconnect_grace_seconds = value;
        }
        if let Some(value) = patch.idle_timeout_seconds {
            next.idle_timeout_seconds = value;
        }
        if let Some(value) = patch.shutdown_timeout_seconds {
            next.shutdown_timeout_seconds = value;
        }
        if let Some(value) = patch.max_backup_bytes {
            next.max_backup_bytes = value;
        }
        validate_settings(&next)?;
        self.disconnect_grace_secs
            .store(next.disconnect_grace_seconds, Ordering::Relaxed);
        self.idle_timeout_secs
            .store(next.idle_timeout_seconds, Ordering::Relaxed);
        self.shutdown_timeout_secs
            .store(next.shutdown_timeout_seconds, Ordering::Relaxed);
        self.max_backup_bytes
            .store(next.max_backup_bytes, Ordering::Relaxed);
        Ok(next)
    }
}

impl Config {
    pub fn from_args(args: Args) -> Result<Self> {
        if !args.listen.ip().is_loopback() {
            return Err(Error::Config(
                "--listen must use a loopback address; remote binding is forbidden".into(),
            ));
        }

        let home = home_dir()?;
        let sessions_dir = args
            .sessions_dir
            .unwrap_or_else(|| home.join(".pi/agent/sessions"));
        let state_dir = args
            .state_dir
            .unwrap_or_else(|| home.join(".local/share/openhouseai/runtime"));
        fs::create_dir_all(&sessions_dir)?;
        fs::create_dir_all(&state_dir)?;
        let sessions_dir = fs::canonicalize(sessions_dir)?;
        let state_dir = fs::canonicalize(state_dir)?;

        let persisted = load_settings(&state_dir.join("runtime-config.json"))?;
        let settings = SettingsSnapshot {
            disconnect_grace_seconds: args
                .disconnect_grace_secs
                .or_else(|| persisted.as_ref().map(|s| s.disconnect_grace_seconds))
                .unwrap_or(DEFAULT_DISCONNECT_GRACE_SECS),
            idle_timeout_seconds: args
                .idle_timeout_secs
                .or_else(|| persisted.as_ref().map(|s| s.idle_timeout_seconds))
                .unwrap_or(DEFAULT_IDLE_TIMEOUT_SECS),
            shutdown_timeout_seconds: args
                .shutdown_timeout_secs
                .or_else(|| persisted.as_ref().map(|s| s.shutdown_timeout_seconds))
                .unwrap_or(DEFAULT_SHUTDOWN_TIMEOUT_SECS),
            max_backup_bytes: args
                .max_backup_bytes
                .or_else(|| persisted.as_ref().map(|s| s.max_backup_bytes))
                .unwrap_or(DEFAULT_MAX_BACKUP_BYTES),
        };
        validate_settings(&settings)?;

        let token_file = args
            .token_file
            .unwrap_or_else(|| state_dir.join("access-token"));
        let token = resolve_token(args.token, &token_file)?;
        let pi_working_dir = args.pi_working_dir.unwrap_or_else(|| home.clone());
        if !pi_working_dir.is_dir() {
            return Err(Error::Config(format!(
                "Pi working directory does not exist: {}",
                pi_working_dir.display()
            )));
        }
        let extension_paths = args
            .extension_paths
            .into_iter()
            .map(|path| {
                fs::canonicalize(&path).map_err(|error| {
                    Error::Config(format!(
                        "Pi extension does not exist ({}): {error}",
                        path.display()
                    ))
                })
            })
            .collect::<Result<Vec<_>>>()?;

        Ok(Self {
            listen: args.listen,
            pi_bin: args.pi_bin,
            sessions_dir,
            state_dir,
            pi_working_dir,
            extension_paths,
            token: Arc::from(token),
            token_file,
            settings: Arc::new(RuntimeSettings::new(&settings)),
        })
    }

    pub fn public(&self) -> PublicConfig {
        PublicConfig {
            listen: self.listen.to_string(),
            pi_bin: self.pi_bin.display().to_string(),
            sessions_dir: self.sessions_dir.display().to_string(),
            state_dir: self.state_dir.display().to_string(),
            pi_working_dir: self.pi_working_dir.display().to_string(),
            extension_paths: self
                .extension_paths
                .iter()
                .map(|path| path.display().to_string())
                .collect(),
            token_file: self.token_file.display().to_string(),
            settings: self.settings.snapshot(),
        }
    }

    pub fn persist_settings(&self, snapshot: &SettingsSnapshot) -> Result<()> {
        atomic_json_write(&self.state_dir.join("runtime-config.json"), snapshot)
    }
}

pub fn atomic_json_write(path: &Path, value: &impl Serialize) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| Error::Config("configuration path has no parent".into()))?;
    fs::create_dir_all(parent)?;
    let temporary = parent.join(format!(".{}.tmp", uuid::Uuid::new_v4()));
    let bytes = serde_json::to_vec_pretty(value)?;
    let mut file = OpenOptions::new()
        .create_new(true)
        .write(true)
        .mode(0o600)
        .open(&temporary)?;
    file.write_all(&bytes)?;
    file.sync_all()?;
    fs::rename(&temporary, path)?;
    Ok(())
}

fn home_dir() -> Result<PathBuf> {
    env::var_os("HOME")
        .filter(|value| !value.is_empty())
        .map(PathBuf::from)
        .ok_or_else(|| Error::Config("HOME is not set".into()))
}

fn resolve_token(explicit: Option<String>, token_file: &Path) -> Result<String> {
    if let Some(token) = explicit {
        validate_token(&token)?;
        return Ok(token);
    }
    if token_file.exists() {
        let token = fs::read_to_string(token_file)?.trim().to_owned();
        validate_token(&token)?;
        return Ok(token);
    }
    if let Some(parent) = token_file.parent() {
        fs::create_dir_all(parent)?;
    }
    let mut bytes = [0_u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    let token = URL_SAFE_NO_PAD.encode(bytes);
    let mut file = OpenOptions::new()
        .create_new(true)
        .write(true)
        .mode(0o600)
        .open(token_file)?;
    file.write_all(token.as_bytes())?;
    file.write_all(b"\n")?;
    file.sync_all()?;
    Ok(token)
}

fn validate_token(token: &str) -> Result<()> {
    if token.len() < 32 || token.contains(char::is_whitespace) {
        return Err(Error::Config(
            "access token must contain at least 32 non-whitespace characters".into(),
        ));
    }
    Ok(())
}

fn validate_settings(settings: &SettingsSnapshot) -> Result<()> {
    if !(1..=300).contains(&settings.disconnect_grace_seconds) {
        return Err(Error::Config(
            "disconnect grace must be between 1 and 300 seconds".into(),
        ));
    }
    if settings.idle_timeout_seconds < settings.disconnect_grace_seconds
        || settings.idle_timeout_seconds > 86_400
    {
        return Err(Error::Config(
            "idle timeout must be >= disconnect grace and <= 86400 seconds".into(),
        ));
    }
    if !(1..=60).contains(&settings.shutdown_timeout_seconds) {
        return Err(Error::Config(
            "shutdown timeout must be between 1 and 60 seconds".into(),
        ));
    }
    if !(1024 * 1024..=4 * 1024 * 1024 * 1024_u64).contains(&settings.max_backup_bytes) {
        return Err(Error::Config(
            "maximum backup size must be between 1 MiB and 4 GiB".into(),
        ));
    }
    Ok(())
}

fn load_settings(path: &Path) -> Result<Option<SettingsSnapshot>> {
    if !path.exists() {
        return Ok(None);
    }
    let settings = serde_json::from_slice(&fs::read(path)?)?;
    Ok(Some(settings))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_remote_listen_address() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let args = Args {
            listen: "0.0.0.0:8765".parse().expect("socket"),
            pi_bin: "pi".into(),
            sessions_dir: Some(temporary.path().join("sessions")),
            state_dir: Some(temporary.path().join("state")),
            pi_working_dir: Some(temporary.path().to_owned()),
            extension_paths: Vec::new(),
            token: Some("x".repeat(32)),
            token_file: None,
            disconnect_grace_secs: None,
            idle_timeout_secs: None,
            shutdown_timeout_secs: None,
            max_backup_bytes: None,
        };
        assert!(matches!(Config::from_args(args), Err(Error::Config(_))));
    }
}
